import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Mood News Grid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="bg-[var(--bg-color)] 
       "
    >
      <body className="overflow-y-hidden">{children}</body>
    </html>
  );
}
